import {
  ShortLink,
  GlobalAnalytics,
  CustomDomain,
  ApiKeyItem,
  ClickDataPoint,
} from "@/types";

export const PREVIEW_LINKS: ShortLink[] = [
  {
    id: "link-1",
    userId: "preview-user",
    slug: "stripe-billing-q4",
    domainName: "lsho.cc",
    shortUrl: "https://lsho.cc/stripe-billing-q4",
    targetUrl: "https://stripe.com/enterprise/billing-portal-v2",
    clicksCount: 42500,
    uniqueClicks: 28900,
    conversionsCount: 38,
    revenue: 1840.5,
    routingRules: [
      { id: "r1", type: "country", country: "FR", targetUrl: "https://stripe.com/fr/enterprise" },
      { id: "r2", type: "device", device: "mobile", targetUrl: "https://stripe.com/mobile/checkout" },
    ],
    geoTargeting: { FR: "https://stripe.com/fr/enterprise", DE: "https://stripe.com/de/enterprise" },
    deviceTargeting: { mobile: "https://stripe.com/mobile/checkout" },
    isPasswordProtected: false,
    isCloaked: true,
    metaTitle: "Stripe Billing Enterprise Portal",
    tags: ["revenue", "stripe", "q4-campaign"],
    isActive: true,
    userFullName: "Alex Moran",
    userName: "Alex Moran",
    userEmail: "alex@acme.io",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 12).toISOString(),
  },
  {
    id: "link-2",
    userId: "preview-user",
    slug: "linear-roadmap-26",
    domainName: "lsho.cc",
    shortUrl: "https://lsho.cc/linear-roadmap-26",
    targetUrl: "https://linear.app/features/roadmaps-nextgen",
    clicksCount: 28910,
    uniqueClicks: 21300,
    conversionsCount: 19,
    revenue: 920.0,
    routingRules: [],
    geoTargeting: {},
    deviceTargeting: {},
    isPasswordProtected: false,
    isCloaked: false,
    metaTitle: "Linear 2026 Product Roadmap",
    tags: ["product", "linear", "growth"],
    isActive: true,
    userFullName: "Carla George",
    userName: "Carla George",
    userEmail: "carla@acme.io",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 18).toISOString(),
  },
  {
    id: "link-3",
    userId: "preview-user",
    slug: "vercel-edge-sdk",
    domainName: "lsho.cc",
    shortUrl: "https://lsho.cc/vercel-edge-sdk",
    targetUrl: "https://vercel.com/docs/edge-network/global-routing",
    clicksCount: 19420,
    uniqueClicks: 14100,
    conversionsCount: 11,
    revenue: 540.0,
    routingRules: [
      { id: "r3", type: "country", country: "US", targetUrl: "https://vercel.com/docs/edge-network/us-east" },
    ],
    geoTargeting: { US: "https://vercel.com/docs/edge-network/us-east" },
    isPasswordProtected: false,
    isCloaked: true,
    metaTitle: "Vercel Edge SDK Documentation",
    tags: ["docs", "developers", "sdk"],
    isActive: true,
    userFullName: "Ekstrom Bothman",
    userName: "Ekstrom Bothman",
    userEmail: "ekstrom@acme.io",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 25).toISOString(),
  },
  {
    id: "link-4",
    userId: "preview-user",
    slug: "summation-deck",
    domainName: "lsho.cc",
    shortUrl: "https://lsho.cc/summation-deck",
    targetUrl: "https://summation.com/platform/pitch-deck-2026",
    clicksCount: 15800,
    uniqueClicks: 11200,
    conversionsCount: 6,
    revenue: 310.0,
    routingRules: [],
    isPasswordProtected: true,
    isCloaked: true,
    pathLockMode: "strict",
    pathLockPrefix: "deck",
    tags: ["investors", "deck", "confidential"],
    isActive: true,
    userFullName: "Emery Culhane",
    userName: "Emery Culhane",
    userEmail: "emery@acme.io",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 32).toISOString(),
  },
  {
    id: "link-5",
    userId: "preview-user",
    slug: "cloudflare-d1-sync",
    domainName: "lsho.cc",
    shortUrl: "https://lsho.cc/cloudflare-d1-sync",
    targetUrl: "https://developers.cloudflare.com/d1/platform-sync",
    clicksCount: 12340,
    uniqueClicks: 9400,
    conversionsCount: 5,
    revenue: 215.0,
    tags: ["infrastructure", "cloudflare", "d1"],
    isActive: true,
    userFullName: "Alex Moran",
    userName: "Alex Moran",
    userEmail: "alex@acme.io",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 40).toISOString(),
  },
  {
    id: "link-6",
    userId: "preview-user",
    slug: "figma-design-tokens",
    domainName: "lsho.cc",
    shortUrl: "https://lsho.cc/figma-design-tokens",
    targetUrl: "https://figma.com/@design-tokens-lshorter",
    clicksCount: 9520,
    uniqueClicks: 6800,
    conversionsCount: 3,
    revenue: 145.0,
    tags: ["design", "tokens", "figma"],
    isActive: true,
    userFullName: "Alex Moran",
    userName: "Alex Moran",
    userEmail: "alex@acme.io",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 45).toISOString(),
  },
  {
    id: "link-7",
    userId: "preview-user",
    slug: "notion-workspace",
    domainName: "lsho.cc",
    shortUrl: "https://lsho.cc/notion-workspace",
    targetUrl: "https://notion.so/acme-corp/product-specs-2026",
    clicksCount: 6420,
    uniqueClicks: 4900,
    conversionsCount: 2,
    revenue: 89.0,
    tags: ["internal", "notion"],
    isActive: true,
    userFullName: "Carla George",
    userName: "Carla George",
    userEmail: "carla@acme.io",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 50).toISOString(),
  },
  {
    id: "link-8",
    userId: "preview-user",
    slug: "reui-telemetry-v2",
    domainName: "lsho.cc",
    shortUrl: "https://lsho.cc/reui-telemetry-v2",
    targetUrl: "https://lsho.cc/docs/telemetry-architecture",
    clicksCount: 3100,
    uniqueClicks: 2500,
    conversionsCount: 1,
    revenue: 45.0,
    tags: ["engineering", "telemetry"],
    isActive: true,
    userFullName: "Ekstrom Bothman",
    userName: "Ekstrom Bothman",
    userEmail: "ekstrom@acme.io",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 60).toISOString(),
  },
];

const now = Date.now();
const oneDayMs = 24 * 60 * 60 * 1000;

export const PREVIEW_CLICKS_BY_DAY: ClickDataPoint[] = Array.from({ length: 30 }, (_, i) => {
  const d = new Date(now - (29 - i) * oneDayMs);
  const dateKey = d.toISOString().split("T")[0];
  const clicks = Math.floor(2800 + Math.sin(i / 3) * 1400 + Math.random() * 800);
  const unique = Math.floor(clicks * 0.72);
  return {
    date: dateKey,
    dayNumber: i + 1,
    clicks,
    uniqueClicks: unique,
    label: d.toLocaleDateString("en-US", { month: "short", day: "numeric" }),
  };
});

export const PREVIEW_ANALYTICS: GlobalAnalytics = {
  totalClicks: 128490,
  clicksGrowth: 18.4,
  uniqueClicks: 84200,
  uniqueClicksGrowth: 12.1,
  trackedRevenue: 3971.5,
  revenueGrowth: 24.8,
  avgCtr: 8.4,
  ctrGrowth: 2.1,
  bounceRate: 24.1,
  epc: 0.031,
  avgEngagementTime: "2m 14s",
  clicksByDay: PREVIEW_CLICKS_BY_DAY,
  topCountries: [
    { code: "US", name: "United States", count: 48200, percentage: 38, lat: 37.0902, lng: -95.7129 },
    { code: "DE", name: "Germany", count: 24100, percentage: 19, lat: 51.1657, lng: 10.4515 },
    { code: "FR", name: "France", count: 19800, percentage: 15, lat: 46.2276, lng: 2.2137 },
    { code: "GB", name: "United Kingdom", count: 16400, percentage: 13, lat: 55.3781, lng: -3.436 },
    { code: "JP", name: "Japan", count: 11200, percentage: 9, lat: 36.2048, lng: 138.2529 },
    { code: "CA", name: "Canada", count: 8790, percentage: 6, lat: 56.1304, lng: -106.3468 },
  ],
  topCities: [
    { city: "San Francisco", countryCode: "US", countryName: "United States", count: 14200, percentage: 22 },
    { city: "Paris", countryCode: "FR", countryName: "France", count: 11400, percentage: 18 },
    { city: "Berlin", countryCode: "DE", countryName: "Germany", count: 9800, percentage: 15 },
    { city: "London", countryCode: "GB", countryName: "United Kingdom", count: 8600, percentage: 13 },
    { city: "Tokyo", countryCode: "JP", countryName: "Japan", count: 6200, percentage: 10 },
  ],
  topDevices: [
    { label: "Desktop", device: "desktop", count: 74500, percentage: 58 },
    { label: "Mobile", device: "mobile", count: 46250, percentage: 36 },
    { label: "Tablet", device: "tablet", count: 7740, percentage: 6 },
  ],
  topBrowsers: [
    { name: "Chrome", count: 66800, percentage: 52 },
    { name: "Safari", count: 35900, percentage: 28 },
    { name: "Firefox", count: 15400, percentage: 12 },
    { name: "Edge", count: 10390, percentage: 8 },
  ],
  topReferrers: [
    { source: "Direct", referrer: "Direct", count: 42100, percentage: 33 },
    { source: "x.com", referrer: "x.com", count: 32400, percentage: 25 },
    { source: "linkedin.com", referrer: "linkedin.com", count: 25800, percentage: 20 },
    { source: "github.com", referrer: "github.com", count: 18200, percentage: 14 },
    { source: "google.com", referrer: "google.com", count: 9990, percentage: 8 },
  ],
  liveClickEvents: [
    {
      id: "evt-1",
      linkId: "link-1",
      timestamp: new Date().toISOString(),
      slug: "stripe-billing-q4",
      ipMasked: "194.204.•••.•••",
      countryCode: "FR",
      countryName: "France",
      city: "Paris",
      device: "Desktop",
      os: "macOS",
      browser: "Chrome 134",
      referrer: "linkedin.com",
    },
    {
      id: "evt-2",
      linkId: "link-2",
      timestamp: new Date(Date.now() - 14000).toISOString(),
      slug: "linear-roadmap-26",
      ipMasked: "72.134.•••.•••",
      countryCode: "US",
      countryName: "United States",
      city: "San Francisco",
      device: "Mobile",
      os: "iOS 18",
      browser: "Safari 18",
      referrer: "x.com",
    },
    {
      id: "evt-3",
      linkId: "link-3",
      timestamp: new Date(Date.now() - 38000).toISOString(),
      slug: "vercel-edge-sdk",
      ipMasked: "88.198.•••.•••",
      countryCode: "DE",
      countryName: "Germany",
      city: "Frankfurt",
      device: "Desktop",
      os: "Windows 11",
      browser: "Firefox",
      referrer: "github.com",
    },
    {
      id: "evt-4",
      linkId: "link-5",
      timestamp: new Date(Date.now() - 65000).toISOString(),
      slug: "cloudflare-d1-sync",
      ipMasked: "82.165.•••.•••",
      countryCode: "GB",
      countryName: "United Kingdom",
      city: "London",
      device: "Desktop",
      os: "Windows 11",
      browser: "Edge",
      referrer: "Direct",
    },
    {
      id: "evt-5",
      linkId: "link-4",
      timestamp: new Date(Date.now() - 110000).toISOString(),
      slug: "summation-deck",
      ipMasked: "133.242.•••.•••",
      countryCode: "JP",
      countryName: "Japan",
      city: "Tokyo",
      device: "Desktop",
      os: "macOS",
      browser: "Chrome",
      referrer: "linkedin.com",
    },
  ],
  recentConversions: [],
};

export const PREVIEW_DOMAINS: CustomDomain[] = [
  {
    id: "dom-1",
    domain: "go.acme.io",
    status: "active",
    linksCount: 14,
    dnsRecords: [
      {
        type: "CNAME",
        name: "go",
        value: "edge.lsho.cc",
        ttl: 300,
        note: "Cloudflare Edge SSL",
      },
    ],
    instructions: ["Add CNAME record pointing to edge.lsho.cc"],
    created_at: "2026-01-15T10:00:00Z",
  },
  {
    id: "dom-2",
    domain: "links.product.com",
    status: "active",
    linksCount: 8,
    dnsRecords: [
      {
        type: "CNAME",
        name: "links",
        value: "edge.lsho.cc",
        ttl: 300,
        note: "Automatic Certificate Authority",
      },
    ],
    instructions: ["Add CNAME record pointing to edge.lsho.cc"],
    created_at: "2026-02-10T14:30:00Z",
  },
  {
    id: "dom-3",
    domain: "share.summation.dev",
    status: "pending",
    linksCount: 3,
    dnsRecords: [
      {
        type: "CNAME",
        name: "share",
        value: "edge.lsho.cc",
        ttl: 300,
        note: "DNS propagation in progress",
      },
    ],
    instructions: ["Add CNAME record pointing to edge.lsho.cc"],
    created_at: "2026-03-22T08:15:00Z",
  },
];

export const PREVIEW_API_KEYS: ApiKeyItem[] = [
  {
    id: "key-1",
    name: "Production Edge Gateway",
    prefix: "lsh_live_9x82",
    scope: "admin",
    created_at: "2026-01-10T11:00:00Z",
    lastUsedAt: "Just now",
  },
  {
    id: "key-2",
    name: "Staging CI/CD Runner",
    prefix: "lsh_test_ab41",
    scope: "read_write",
    created_at: "2026-02-18T16:20:00Z",
    lastUsedAt: "2 hours ago",
  },
];

export const PREVIEW_MONTHLY_BARS = [
  { label: "Jan", fullDate: "January 2026", primary: 8420, secondary: 6100 },
  { label: "Feb", fullDate: "February 2026", primary: 9640, secondary: 7200 },
  { label: "Mar", fullDate: "March 2026", primary: 11200, secondary: 8450 },
  { label: "Apr", fullDate: "April 2026", primary: 14800, secondary: 11100 },
  { label: "May", fullDate: "May 2026", primary: 12900, secondary: 9800 },
  { label: "Jun", fullDate: "June 2026", primary: 15400, secondary: 11900 },
  { label: "Jul", fullDate: "July 2026", primary: 13200, secondary: 10100 },
  { label: "Aug", fullDate: "August 2026", primary: 14900, secondary: 11400 },
  { label: "Sep", fullDate: "September 2026", primary: 16890, secondary: 12900 },
  { label: "Oct", fullDate: "October 2026", primary: 14200, secondary: 10800 },
  { label: "Nov", fullDate: "November 2026", primary: 13800, secondary: 10200 },
  { label: "Dec", fullDate: "December 2026", primary: 15140, secondary: 11400 },
];
